name = "apush-demo"
main = "worker.js"
compatibility_date = "2026-06-01"

# 静态前端（管理界面 + 资源）由 Cloudflare Assets 托管
[assets]
directory = "../public"
binding = "ASSETS"

# 自定义域名绑定（apush.me 已在 Cloudflare）
domains = ["apush.me"]
